blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("blog", views.homepage, name="homepage"),
    path("newsletter", views.newsletter, name="newsletter"),
    path("new_post", views.new_post, name="post-create"),
    path("<str:article>", views.article, name="article"),
    path("<article>/update", views.article_update, name="article_update"),
    path("<article>/delete", views.article_delete, name="article_delete"),
    path("<article>/upload_image", views.upload_image, name="upload_image"),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('shop.urls')),
    path('',include('users.urls')),
    path('',include('blog.urls')),
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('_nested_admin/', include('nested_admin.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include("allauth.urls")),
]
admin.site.site_header  =  "The Team Apparel"  
admin.site.site_title  =  "The Team Apparel site"
admin.site.index_title  =  "The Team Apparel"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path,include
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns=[
    path('',views.home,name='home'),
    path('search',views.search,name='search'),
    path('category-list',views.category_list,name='category-list'),
    path('brand-list',views.brand_list,name='brand-list'),
    path('product-list',views.product_list,name='product-list'),
    path('category-product-list/<int:cat_id>',views.category_product_list,name='category-product-list'),
    path('product_discount/<int:banner_id>',views.product_discount,name='product_discount'),
    path('brand-product-list/<int:brand_id>',views.brand_product_list,name='brand-product-list'),
    path('product/<str:slug>/<int:id>',views.product_detail,name='product_detail'),
    path('productattribute/<int:id>',views.product_attribute_detail,name='product_attribute_detail'),
    path('filter-data',views.filter_data,name='filter_data'),
    path('load-more-data',views.load_more_data,name='load_more_data'),
    path('add-to-cart',views.add_to_cart,name='add_to_cart'),
    path('add-to-cart-attribute',views.add_to_cart_attribute,name='add_to_cart_attribute'),
    path('cart',views.cart_list,name='cart'),    
    path('delete-from-cart',views.delete_cart_item,name='delete-from-cart'),
    path('update-cart',views.update_cart_item,name='update-cart'),
    path('checkout',views.checkout,name='checkout'),
    path('create-checkout-session/', views.CreateCheckoutSessionView, name='create-checkout-session'),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment-processing/', views.payment_processing, name='payment_processing'),
    path('payment-done/', views.payment_done, name='payment_done'),
    path('payment-cancelled/', views.payment_canceled, name='payment_cancelled'),
    path('save-review/<int:pid>',views.save_review, name='save-review'),

    # Contact
    path('contact', views.contact, name='contact'),

    # User Section Start
    path('my-dashboard',views.my_dashboard, name='my_dashboard'),
    path('my-orders',views.my_orders, name='my_orders'),
    path('my-orders-items/<int:id>',views.my_order_items, name='my_order_items'),
    # End

    # Wishlist
    path('add-wishlist',views.add_wishlist, name='add_wishlist'),
    path('delete-wishlist',views.delete_wishlist, name='delete_wishlist'),
    path('my-wishlist',views.my_wishlist, name='my_wishlist'),
    # My Reviews
    path('my-reviews',views.my_reviews, name='my-reviews'),
    path('delete-review',views.delete_review, name='delete-review'),
    # My AddressBook
    path('my-addressbook',views.my_addressbook, name='my-addressbook'),
    path('add-address',views.save_address, name='add-address'),
    path('activate-address',views.activate_address, name='activate-address'),
    path('update-address/<int:id>',views.update_address, name='update-address'),
    path('edit-profile',views.edit_profile, name='edit-profile'),
]

shop/models.py
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone
from tinymce.models import HTMLField

class Banner(models.Model):
    title=models.CharField(max_length=200)
    desc=models.CharField(max_length=500)
    discount_1=models.IntegerField(validators=[MinValueValidator(0.0), MaxValueValidator(100.0)],default=0.0)
    discount_2=models.IntegerField(validators=[MinValueValidator(0.0), MaxValueValidator(100.0)],default=0.0)
    img=models.ImageField(upload_to="banner_imgs/")
    alt_text=models.CharField(max_length=300)

    class Meta:
        verbose_name_plural='Banners'

    def image_tag(self):
        return mark_safe('<img src="%s" width="100" />' % (self.img.url))

    def __str__(self):
        return self.alt_text

# Category
class Category(models.Model):
    title=models.CharField(max_length=100)
    image=models.ImageField(upload_to="cat_imgs/")
    desc=models.CharField(max_length=1000)

    class Meta:
        verbose_name_plural='Categories'

    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.title

# Brand
class Brand(models.Model):
    title=models.CharField(max_length=100)
    image=models.ImageField(upload_to="brand_imgs/")

    class Meta:
        verbose_name_plural='Brands'

    def __str__(self):
        return self.title
    
    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

# Color
class Color(models.Model):
    title=models.CharField(max_length=100)
    color_code=models.CharField(max_length=100)

    class Meta:
        verbose_name_plural='Colors'

    def color_bg(self):
        return mark_safe('<div style="width:30px; height:30px; background-color:%s"></div>' % (self.color_code))

    def __str__(self):
        return self.title

# Size
class Size(models.Model):
    title=models.CharField(max_length=100)
    size_code=models.CharField(max_length=10)

    class Meta:
        verbose_name_plural='Sizes'

    def __str__(self):
        return self.title

# Product Model
class Product(models.Model):
    title=models.CharField(max_length=200)
    slug=models.CharField(max_length=400)
    sku=models.CharField(max_length=100)
    description=HTMLField(blank=True, default="")
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    brand=models.ForeignKey(Brand,on_delete=models.CASCADE)
    status=models.BooleanField(default=True)
    is_featured=models.BooleanField(default=False)
    created_on = models.DateTimeField("created on", default=timezone.now)

    class Meta:
        verbose_name_plural='Products'

    def __str__(self):
        return self.title

#Product Attribute Pictures
class ProductAttributePictures(models.Model):
    name = models.CharField(max_length=500)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural='Product Attribute Pictures'

class Images(models.Model):
    picture = models.ImageField(upload_to='shop/product_images', null=True, blank=True)  
    product = models.ForeignKey(ProductAttributePictures, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural='Images'

# Product Attribute
class ProductAttribute(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    color=models.ForeignKey(Color,on_delete=models.CASCADE)
    size=models.ForeignKey(Size,on_delete=models.CASCADE)
    price=models.FloatField(validators=[MinValueValidator(0.0)], default=0)
    discount=models.IntegerField(validators=[MinValueValidator(0.0), MaxValueValidator(100.0)],default=0.0)
    quantity=models.PositiveIntegerField(default=0)
    sell_price=models.FloatField(null=True, validators=[MinValueValidator(0.0)])
    image=models.ForeignKey(ProductAttributePictures, on_delete=models.CASCADE, default=1)

    @property
    def sell_price(self):
        discount = 100 - self.discount
        discount_num = discount/100
        discount_num_b = float(discount_num)
        total = self.price*discount_num_b
        return round(total, 1)

    class Meta:
        verbose_name_plural='Product Attributes'

    def __str__(self):
        return self.product.title

    #def image_tag(self):
        #return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

# Product Tags
class ProductTag(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    tag_name=models.CharField(max_length=500)

    def __str__(self):
        return self.tag_name
    class Meta:
        verbose_name_plural='Product Tags'

# Order
status_choice=(
        ('processing','In Process'),
        ('shipped','Shipped'),
        ('delivered','Delivered'),
    )

class Cart(models.Model):
    user=models.ForeignKey(get_user_model(),on_delete=models.CASCADE)
    product_attribute=models.ForeignKey(ProductAttribute,on_delete=models.CASCADE)
    qty=models.PositiveBigIntegerField()

    def __str__(self):
        return self.product_attribute.product.title

    class Meta:
        verbose_name_plural='Cart Items'

# AddressBook
class Countries(models.Model):
    country_name=models.CharField(max_length=1000)
    delivery_price=models.FloatField(default=25.0)

    def __str__(self):
        return self.country_name
    
    class Meta:
        verbose_name_plural='Countries'

# AddressBook
class UserAddressBook(models.Model):
    user=models.ForeignKey(get_user_model(),on_delete=models.CASCADE)
    address_name=models.CharField(max_length=1000)
    country=models.ForeignKey(Countries, on_delete=models.CASCADE, default=1)
    town_or_city=models.CharField(max_length=1000)
    address=models.CharField(max_length=1000)
    postal_code=models.IntegerField()
    mobile=models.CharField(max_length=50,null=True)
    status=models.BooleanField(default=False)

    def __str__(self):
        return self.country.country_name

    class Meta:
        verbose_name_plural='Address Book'

class CartOrder(models.Model):
    user=models.ForeignKey(get_user_model(),on_delete=models.CASCADE)
    total_amt=models.FloatField()
    address=models.ForeignKey(UserAddressBook, on_delete=models.CASCADE)
    order_dt=models.DateTimeField(auto_now_add=True)
    order_status=models.CharField(choices=status_choice,default='processing',max_length=150)
    paid_status=models.BooleanField(default=False)

    class Meta:
        verbose_name_plural='Orders'

# OrderItems
class CartOrderItems(models.Model):
    order=models.ForeignKey(CartOrder,on_delete=models.CASCADE)
    invoice_no=models.CharField(max_length=150)
    item=models.CharField(max_length=150)
    image=models.CharField(max_length=200)
    qty=models.IntegerField()
    price=models.FloatField()
    total=models.FloatField()

    def __str__(self):
        return self.invoice_no
    
    class Meta:
        verbose_name_plural='Order Items'

    def image_tag(self):
        return mark_safe('<img src="/media/%s" width="50" height="50" />' % (self.image))

# Product Review
RATING=(
    (1,1),
    (2,2),
    (3,3),
    (4,4),
    (5,5),
)
class ProductReview(models.Model):
    user=models.ForeignKey(get_user_model(),on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    review_text=models.TextField()
    review_rating=models.IntegerField(choices=RATING)

    class Meta:
        verbose_name_plural='Reviews'

    def get_review_rating(self):
        return self.review_rating

# WishList
class Wishlist(models.Model):
    user=models.ForeignKey(get_user_model(),on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural='Wishlist'



 

shop/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from .models import ProductReview,UserAddressBook

class SignupForm(UserCreationForm):
	class Meta:
		model=User
		fields=('first_name','last_name','email','username','password1','password2')

# Review Add Form
class ReviewAdd(forms.ModelForm):
	class Meta:
		model=ProductReview
		fields=('review_text','review_rating')

# AddressBook Add Form
class AddressBookForm(forms.ModelForm):
	class Meta:
		model=UserAddressBook
		fields=('address_name','country','town_or_city','address','postal_code','mobile','status')

# ProfileEdit
class ProfileForm(UserChangeForm):
	class Meta:
		model=User
		fields=('first_name','last_name','email','username')


# Contact Form
class ContactForm(forms.Form):
	name = forms.CharField(widget=forms.TextInput(
        attrs={'class': '', 'placeholder': 'Name'}),
        label="Name*")
	email_address = forms.CharField(widget=forms.TextInput(
        attrs={'class': '', 'placeholder': 'Email'}),
        label="Email*")
	message = forms.CharField(widget = forms.Textarea(
		attrs={'class': '', 'placeholder': 'Message'}),
		label="Message*")

shop/templates/products/blog_section.html
{% load static %}
    <!-- Latest Blog Section Begin -->
    <section class="latest spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title">
                        <span>Latest News</span>
                        <h2>Fashion New Trends</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for articles in article %}
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="blog__item">
                        <div class="blog__item__pic set-bg" data-setbg="{{articles.image.url}}"></div>
                        <div class="blog__item__text">
                            <span><img src="{% static 'media/images/icons/calendar.png' %}" alt="">{{articles.published|date:"F d, Y"}}</span>
                            <h5>{{articles.title}}</h5>
                            <a href="{% url 'article' articles.slug %}">Read More</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <!-- Latest Blog Section End -->

shop/templates/products/index.html
{% extends 'includes/base.html' %}
{% load static %}
{% block content %}
    {% include 'products/product_hero_section.html' %}
    {% include 'products/product_categories_section.html' %}
    {% include 'products/product_section.html' %}
    {% include 'products/blog_section.html' %}
{% endblock %}

shop/templates/products/product_list.html
{% extends 'includes/base.html' %}
{% load custom_tags %}
{% load static %}
{% block content %}
<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-option">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="breadcrumb__text">
					<h4>Products</h4>
					<div class="breadcrumb__links">
						<a href="{% url 'home' %}">Home</a>
						<span>Products</span>
					</div>
				</div>
			</div>
		</div>
	</div>
 </section>
 <!-- Breadcrumb Section End -->

 <!-- Shop Section Begin -->
<section class="shop spad">
	<div class="container">
		<div class="row">
			<div class="col-lg-3">
				<div class="shop__sidebar">
					<div class="shop__sidebar__search">
						<form action="#">
							<input type="text" placeholder="Search...">
							<button type="submit"><span class="icon_search"></span></button>
						</form>
					</div>
					{% include 'filters.html' %}
				</div>
			</div>
			<div class="col-lg-9">
				<div class="row" id="filteredProducts">
					<p class="ajaxLoader">Loading...</p>
					{% for product in data %}
					<div class="col-lg-3 col-md-6 col-sm-6 col-md-6 col-sm-6 product-box">
						<div class="product__item sale get_product_id" data-productid="{{product.id}}">
							<div class="product__item__pic set-bg product-home-image-{{product.id}}" data-setbg="{{product.productattribute_set.first.image.images_set.first.picture.url}}">
								{% get_product_image product as get_image %}
								{% for images in get_image %}
								<div style="display: none;" class="image{{images.color__id}}{{product.id}}" data-image-{{product.id}}="{{images.image__images__picture}}"></div>
								{% endfor %}
								{% if product.productattribute_set.first.sell_price != product.productattribute_set.first.price %}
								<span class="label" style="background-color: red;"><span class="product-discount-label-{{product.id}}">{{product.productattribute_set.first.discount}}</span>% off</span>
								{% else %}
								<!-- <span class="label">New</span> -->
								{% endif %}
								<ul class="product__hover">
									{% if user.is_authenticated %}
									<li><button class="add-wishlist" data-product="{{product.id}}" style="padding: 0px; border: 0px;"><img src="{% static 'media/images/icons/heart.png' %}" alt=""></button></li>
									{% else %}
									{% endif %}
									<li><a href="/product/{{product.slug}}/{{product.id}}"><img src="{% static 'media/images/icons/search.png' %}" alt=""><span>View Product</span></a></li>
								</ul>
							</div>
							<div class="product__item__text">
								<h6 style="font-size: 12px; color: rgb(147, 147, 147);">{{product.category|upper}}</h6>
								<h6>{{product.title}}</h6>
												
								<input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
								<input type="hidden" class="product-image-{{product.id}}" value="{{product.productattribute_set.first.image}}" />
								<input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}" />
								<input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}" />
								<button class="add-cart add-to-cart" data-index="{{product.id}}">+ Add To Cart</button>
								<div class="rating">
									{% get_avg_product_rating product as avg_reviews %}
									{% if avg_reviews.avg_rating == None %}
									<i class="fa fa-star-o"></i>
									<i class="fa fa-star-o"></i>
									<i class="fa fa-star-o"></i>
									<i class="fa fa-star-o"></i>
									<i class="fa fa-star-o"></i>
									<i class="fa fa-star-i"></i>							
									{% elif avg_reviews.avg_rating == 1 %}
									<i class="fa fa-star"></i>
									<i class="fa fa-star-o"></i>
									<i class="fa fa-star-o"></i>
									<i class="fa fa-star-o"></i>
									<i class="fa fa-star-o"></i>
									<i class="fa fa-star-i"></i>	
									{% elif avg_reviews.avg_rating == 2 %}
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star-o"></i>
									<i class="fa fa-star-o"></i>
									<i class="fa fa-star-o"></i>
									<i class="fa fa-star-i"></i>	
									{% elif avg_reviews.avg_rating == 3 %}
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star-o"></i>
									<i class="fa fa-star-o"></i>
									<i class="fa fa-star-i"></i>	
									{% elif avg_reviews.avg_rating == 4 %}
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star-o"></i>
									<i class="fa fa-star-i"></i>	
									{% elif avg_reviews.avg_rating == 5 %}
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star-i"></i>	
									{% endif %}
								</div>
								<h5>
									<span class="product-price-{{product.id}}">
										{% if user.is_authenticated %}
											{% get_price user product.productattribute_set.first.price product.productattribute_set.first.discount %}
										{% else %}
											{% get_price_session request product.productattribute_set.first.price product.productattribute_set.first.discount %}
										{% endif %}
									</span>
									{% if product.productattribute_set.first.discount == 0 %}
									{% else %}
									<span class="product-discount-{{product.id}}" style="text-decoration: line-through; font-size: 20px; font-weight: 400; color: #b7b7b7; padding-left: 8px;">
										{% if user.is_authenticated %}
											{% get_discount_price user product.productattribute_set.first.price %}
										{% else %}
											{% get_discount_price_session request product.productattribute_set.first.price %}
										{% endif %}
									</span>
									{% endif %}
								</h5>
			
								<div class="product__color__select">
									{% get_product_color product.id as product_colors %}
									{% for color in product_colors%}
										<label class="choose-color" data-color="{{color.color__id}}" style="background-color: {{color.color__color_code}}" for="sp-1">
											<input type="radio" id="{{color.color__color_code}}">
										</label>
									{% endfor %}
									
								<div class="product__size__select">  
									{% get_product_size product.id as product_sizes %}
									{% for size in product_sizes %}
									<label class="choose-size color{{size.color__id}}" data-size="{{size.size__id}}" data-price-{{product.id}}="{% if user.is_authenticated %}{% get_price user size.price size.discount %}{% else %}{% get_price_session request size.price size.discount %}{% endif %}" data-discount-{{product.id}}="{% if user.is_authenticated %}{% get_discount_price user size.price %}{% else %}{% get_discount_price_session request size.price %}{% endif %}" data-discountlabel-{{product.id}}="{{size.discount}}" for="{{size.size__size_code}}">{{size.size__size_code}}
										<input type="radio" id="{{size.size__size_code}}">
									</label>
									{% endfor %}
								</div>
								</div>
							</div>
						</div>
					</div> 
			{% endfor %}
			</div>
			<p class="my-4 text-center"><button id="loadMore" data-total="{{total_data}}" data-limit="3" class="btn btn-dark btn-sm">Load More <i class="fa fa-sync load-more-icon"></i></button></p>
		</div>
	</div>
</section>
<!-- Shop Section End -->
{% endblock %}

shop/templates/products/product_section.html
{% load static %}
{% load custom_tags %}
<!-- Product Section Begins -->
<section class="product spad">
<div class="container">     
    <div class="row">
        <div class="col-lg-12">
            <div class="section-title">
                <span>Featured Products</span>
                <h2>Our Featured Apparels</h2>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <ul class="filter__controls">
                <li class="active" data-filter="*">Featured</li>
                <li data-filter=".new-arrivals">New Arrivals</li>
                <li data-filter=".hot-sales">Hot Sales</li>
            </ul>
        </div>
    </div>
    <div class="row product__filter">  
    {% for product in data %}
        <div class="col-lg-3 col-md-6 col-sm-6 col-md-6 col-sm-6 mix {% if product.productattribute_set.first.sell_price != product.productattribute_set.first.price %}hot-sales{% else %}new-arrivals{% endif %}">
            <div class="product__item sale get_product_id" data-productid="{{product.id}}">
                <div class="product__item__pic set-bg product-home-image-{{product.id}}" data-setbg="{{product.productattribute_set.first.image.images_set.first.picture.url}}">
                    {% get_product_image product as get_image %}
                    {% for images in get_image %}
                    <div style="display: none;" class="image{{images.color__id}}{{product.id}}" data-image-{{product.id}}="{{images.image__images__picture}}"></div>
                    {% endfor %}
                    {% if product.productattribute_set.first.sell_price != product.productattribute_set.first.price %}
                    <span class="label" style="background-color: red;"><span class="product-discount-label-{{product.id}}">{{product.productattribute_set.first.discount}}</span>% off</span>
                    {% else %}
                    <span class="label">New</span>
                    {% endif %}
                    <ul class="product__hover">
                        {% if user.is_authenticated %}
                        <li><button class="add-wishlist" data-product="{{product.id}}" style="padding: 0px; border: 0px;"><img src="{% static 'media/images/icons/heart.png' %}" alt=""></button></li>
                        {% else %}
                        {% endif %}
                        <li><a href="/product/{{product.slug}}/{{product.id}}"><img src="{% static 'media/images/icons/search.png' %}" alt=""><span>View Product</span></a></li>
                    </ul>
                </div>
                <div class="product__item__text">
                    <h6 style="font-size: 12px; color: rgb(147, 147, 147);">{{product.category|upper}}</h6>
                    <h6>{{product.title}}</h6>
                                    
                    <input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
                    <input type="hidden" class="product-image-{{product.id}}" value="{{product.productattribute_set.first.image}}" />
                    <input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}" />
                    <input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}" />
                    <button class="add-cart add-to-cart" data-index="{{product.id}}">+ Add To Cart</button>
                    <div class="rating">
                        {% get_avg_product_rating product as avg_reviews %}
                        {% if avg_reviews.avg_rating == None %}
                        <i class="fa fa-star-o"></i>
                        <i class="fa fa-star-o"></i>
                        <i class="fa fa-star-o"></i>
                        <i class="fa fa-star-o"></i>
                        <i class="fa fa-star-o"></i>
                        <i class="fa fa-star-i"></i>							
                        {% elif avg_reviews.avg_rating == 1 %}
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star-o"></i>
                        <i class="fa fa-star-o"></i>
                        <i class="fa fa-star-o"></i>
                        <i class="fa fa-star-o"></i>
                        <i class="fa fa-star-i"></i>	
                        {% elif avg_reviews.avg_rating == 2 %}
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star-o"></i>
                        <i class="fa fa-star-o"></i>
                        <i class="fa fa-star-o"></i>
                        <i class="fa fa-star-i"></i>	
                        {% elif avg_reviews.avg_rating == 3 %}
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star-o"></i>
                        <i class="fa fa-star-o"></i>
                        <i class="fa fa-star-i"></i>	
                        {% elif avg_reviews.avg_rating == 4 %}
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star-o"></i>
                        <i class="fa fa-star-i"></i>	
                        {% elif avg_reviews.avg_rating == 5 %}
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star-i"></i>	
                        {% endif %}
                    </div>
                    <h5>
                        <span class="product-price-{{product.id}}">
                            {% if user.is_authenticated %}
                                {% get_price user product.productattribute_set.first.price product.productattribute_set.first.discount %}
                            {% else %}
                                {% get_price_session request product.productattribute_set.first.price product.productattribute_set.first.discount %}
                            {% endif %}
                        </span>
                        {% if product.productattribute_set.first.discount == 0 %}
                        {% else %}
                        <span class="product-discount-{{product.id}}" style="text-decoration: line-through; font-size: 20px; font-weight: 400; color: #b7b7b7; padding-left: 8px;">
                            {% if user.is_authenticated %}
                                {% get_discount_price user product.productattribute_set.first.price %}
                            {% else %}
                                {% get_discount_price_session request product.productattribute_set.first.price %}
                            {% endif %}
                        </span>
                        {% endif %}
                    </h5>

                    <div class="product__color__select">
                        {% get_product_color product.id as product_colors %}
                        {% for color in product_colors%}
                            <label class="choose-color" data-color="{{color.color__id}}" style="background-color: {{color.color__color_code}}" for="sp-1">
                                <input type="radio" id="{{color.color__color_code}}">
                            </label>
                        {% endfor %}
                        
                    <div class="product__size__select">  
                        {% get_product_size product.id as product_sizes %}
                        {% for size in product_sizes %}
                        <label class="choose-size color{{size.color__id}}" data-size="{{size.size__id}}" data-price-{{product.id}}="{% if user.is_authenticated %}{% get_price user size.price size.discount %}{% else %}{% get_price_session request size.price size.discount %}{% endif %}" data-discount-{{product.id}}="{% if user.is_authenticated %}{% get_discount_price user size.price %}{% else %}{% get_discount_price_session request size.price %}{% endif %}" data-discountlabel-{{product.id}}="{{size.discount}}" for="{{size.size__size_code}}">{{size.size__size_code}}
                            <input type="radio" id="{{size.size__size_code}}">
                        </label>
                        {% endfor %}
                    </div>
                    </div>
                </div>
            </div>
        </div> 
    {% endfor %}
    </div>
</div>
<p class="my-4 text-center"><a href="{% url 'product-list' %}" class="btn btn-dark btn-sm">All Products <i class="fa fa-long-arrow-alt-right"></i></a></p>
</section>
<!-- Product Section End -->